# HW01

## 1. Импорт библиотеки NumPy

In [6]:
import numpy as np

[1 2 3 4 5 6] [          0      142142     1241234 12312123214]
Двумерный массив: 
 [[1 2 3 4]
 [5 6 7 8]]


## 2. Примеры создания массивов

### 2.1. Из обычных списков

In [17]:
# из списка
a = np.array([0, 142, 3453, 3242])
print("Вектор из обычного списка: ", a, "\nТип: ", type(a), "\nФорма: ", a.shape)

Вектор из обычного списка:  [   0  142 3453 3242] 
Тип:  <class 'numpy.ndarray'> 
Форма:  (4,)


In [19]:
# из двумерного списка
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Двумерный массив из двумерного списка: \n", b, "\nТип: ", type(b), "\nФорма: ", b.shape)

Двумерный массив из двумерного списка: 
 [[1 2 3 4]
 [5 6 7 8]] 
Тип:  <class 'numpy.ndarray'> 
Форма:  (2, 4)


### 2.2. С использованием функций из библиотеки NumPy

#### 2.2.1. np.zeros
np.zeros возвращает массив заданной формы, заполненный нулями

In [26]:
a = np.zeros((5, 5))
print("Двумерный массив 5 x 5, заполненный нулями: \n", a, "\nТип: ", type(a), "\nФорма: ", a.shape)

Двумерный массив 5 x 5, заполненный нулями: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
Тип:  <class 'numpy.ndarray'> 
Форма:  (5, 5)


#### 2.2.2. np.ones
np.ones возвращает массив заданной формы, заполенный единицами

In [27]:
a = np.ones((3, 3, 3))
print("Трехмерный массив 3 x 3 x 3, заполенный единицами: ", a, "\nТип: ", type(a), "\nФорма: ", a.shape)

Трехмерный массив 3 x 3 x 3, заполенный единицами:  [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]] 
Тип:  <class 'numpy.ndarray'> 
Форма:  (3, 3, 3)


#### 2.2.3 np.arange
np.arange возвращает массив из последовательности чисел по заданному началу, концу и шагу

In [29]:
a = np.arange(1, 50, 2)
print("Массив из последовательности чисел от 1 до 50 с шагом 2: ", a, "\nТип: ", type(a), "\nФорма: ", a.shape)

Массив из последовательности чисел от 1 до 50 с шагом 2:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49] 
Тип:  <class 'numpy.ndarray'> 
Форма:  (25,)


In [31]:
a = np.array([np.arange(1, 50, 2), np.arange(1, 50, 2)])
print(a)

[[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
  49]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
  49]]


#### 2.2.4 np.reshape
np.reshape изменяет форму массива, не меняя данные в нем
- число элементов должно совпадать
- один из размеров можно оставить равным -1, тогда NumPy сам вычислит его

In [41]:
a = np.arange(-25, 25).reshape (5, 10)
b = np.arange(0, 30).reshape(2, 3, -1)
print("Двумерный массив 5 x 10 из последовательности чисел от -25 до 24: ", a)
print("Трехмерный массив 2 x 3 x 5 из последовательности чисел от 0 до 29: ", b)

Двумерный массив 5 x 10 из последовательности чисел от -25 до 24:  [[-25 -24 -23 -22 -21 -20 -19 -18 -17 -16]
 [-15 -14 -13 -12 -11 -10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1   0   1   2   3   4]
 [  5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24]]
Трехмерный массив 2 x 3 x 5 из последовательности чисел от 0 до 29:  [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


## 3. Индексирование и срезы

### 3.1 Получение и изменение отдельного элемента

In [68]:
a = np.arange(1, 6) ** 2
print("Массив: ", a)
print("Третий элемент массива: ", a[2])
a[2] = 500
print("Массив после изменения третьего элемента: ", a)

Массив:  [ 1  4  9 16 25]
Третий элемент массива:  9
Массив после изменения третьего элемента:  [  1   4 500  16  25]


### 3.2 Получение и изменение среза элементов массива
NumPy срез - "окно" в массив, от которого он взят (т.е. при изменении элемента в NumPy срезе это отразится на оригинальном массиве)

In [83]:
a = np.arange(1, 10, 2)
print("Массив: ", a)
b = a[0:3]
print("Срез:", b)
a[0:3] = a[0:3] ** 2
print("Массив после изменения элементов с индексами от 0 до 3", a)
b[0] = 12345
print("Срез после изменения первого элемента: ", b)
print("Массив после изменения элемента в срезе: ", a)

Массив:  [1 3 5 7 9]
Срез: [1 3 5]
Массив после изменения элементов с индексами от 0 до 3 [ 1  9 25  7  9]
Срез после изменения первого элемента:  [12345     9    25]
Массив после изменения элемента в срезе:  [12345     9    25     7     9]


### 3.3 Разворот массива

In [84]:
a = np.arange(1, 10)
print("Массив: ", a)
print("Развернутый массив: ", a[::-1])

Массив:  [1 2 3 4 5 6 7 8 9]
Развернутый массив:  [9 8 7 6 5 4 3 2 1]


### 3.4 Итерирование по массиву

In [102]:
a = np.arange(20).reshape(4, 5)
print("Массив :\n", a)
for el in a.flat:
    print(el)

Массив :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


## 4. Векторные операции и базовые статистики

### 4.1. Агрегирующие функции

In [104]:
a = np.array((np.arange(10, 19), np.arange(-9, 0), np.arange(1, 10)))
print("Массив: \n", a)
print("Сумма элементов: ", np.sum(a))
print("Минимальный элемент: ", a.min())
print("Максимальный элемент: ", a.max())
print("Минимумы каждой строки: ", a.min(axis=1))
print("Максимумы каждой строки: ", a.max(axis=1))
print("Среднее: ", a.mean())

Массив: 
 [[10 11 12 13 14 15 16 17 18]
 [-9 -8 -7 -6 -5 -4 -3 -2 -1]
 [ 1  2  3  4  5  6  7  8  9]]
Сумма элементов:  126
Минимальный элемент:  -9
Максимальный элемент:  18
Минимумы каждой строки:  [10 -9  1]
Максимумы каждой строки:  [18 -1  9]
Среднее:  4.666666666666667


### 4.2. Поэлементное сложение и умножение

In [103]:
a = np.array([[1, 2], [3, 4]])
print("Первый массив: \n", a)
b = np.array([[10, 20], [30, 40]])
print("Второй массив : \n", b)

print("Поэлементная сумма: \n", a + b)
print("Поэлементное умножение: \n", a * b)

Первый массив: 
 [[1 2]
 [3 4]]
Второй массив : 
 [[10 20]
 [30 40]]
Поэлементная сумма: 
 [[11 22]
 [33 44]]
Поэлементное умножение: 
 [[ 10  40]
 [ 90 160]]
